# TODO: Translation updated at 2022-11-18 03:04
translate chinese strings:

  # game/options.rpy:15
  old "Kill or Love"
  new ""

  # game/options.rpy:32
  old "{size=+12}{color=FF4444}Writing{/color}{/size}\n\n{font=Roboto-Regular.ttf}Andy Church {size=-8}{a=https://twitter.com/AndyChurch_}[link]{/a}{/size}{/font}\n\n\n\n{size=+12}{color=FF4444}Character Art{/color}{/size}\n\n{font=Roboto-Regular.ttf}tan {size=-8}{a=https://www.deviantart.com/tanuma-san}[link]{/a}{/size}{/font}\n\n\n\n{size=+12}{color=FF4444}Coding{/color}{/size}\n\n{font=Roboto-Regular.ttf}Andy Church{/font}\n\n\n\n{size=+12}{color=FF4444}Testing{/color}{/size}\n\n{font=Roboto-Regular.ttf}FerventWriter\n\nSku;Te\n\nJohan\n\neeveetron\n\nRoger Wallace Jr.{/font}\n\n\n\n{size=+12}{color=FF4444}Music{/color}{/size}\n\n{size=-5}{font=Roboto-Regular.ttf}\"Atlantean Twilight\", \"Clean Soul\", \"Clear Waters\", \"Colorless Aura\", \"Gymnopedie No. 2\", \"Loss\", \"Lost Time\", \"Luminous Rain\", \"Moonstone\", \"Ossuary 2 - Turn\", \"Piece for Disaffected Piano One\", \"Piece for Disaffected Piano Two\"\n\nKevin MacLeod (incompetech.com)\n\nLicensed under Creative Commons: By Attribution 3.0\n\nhttp://creativecommons.org/licenses/by/3.0/{/font}{/size}\n\n\n\n{size=+12}{color=FF4444}Sound Effects{/color}{/size}\n\n{size=-5}{font=Roboto-Regular.ttf}\"Digging1.wav\" by cameronmusic (freesound.org/people/cameronmusic/sounds/138411/)\n\n\"Table Hit.mp3\" by Dasgoat (freesound.org/people/Dasgoat/sounds/332034/)\n\n\"Smashing, Wooden Fence, B.wav\" by InspectorJ (freesound.org/people/InspectorJ/sounds/352204/)\n\n\"OhDearScare.wav\" by SirBedlam (freesound.org/people/SirBedlam/sounds/124954/)\n\n\"Heartbeat.wav\" by TobiasLudwig (freesound.org/people/TobiasLudwig/sounds/387072/)\n\nLicensed under Creative Commons: By Attribution 3.0\n\nhttp://creativecommons.org/licenses/by/3.0/{/font}{/size}\n\n\n\n{size=+12}{color=FF4444}Engine{/color}{/size}\n\n{size=-5}{font=Roboto-Regular.ttf}Made with {a=https://www.renpy.org/}Ren'Py{/a} 7.3.2.320.\n\nThis program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}.{/font}{/size}\n\n\n\n"
  new "{size=+12}{color=FF4444}Writing{/color}{/size}\n\n{font=NotoSansSC-Regular.otf}Andy Church {size=-8}{a=https://twitter.com/AndyChurch_}[link]{/a}{/size}{/font}\n\n\n\n{size=+12}{color=FF4444}Character Art{/color}{/size}\n\n{font=NotoSansSC-Regular.otf}tan {size=-8}{a=https://www.deviantart.com/tanuma-san}[link]{/a}{/size}{/font}\n\n\n\n{size=+12}{color=FF4444}Coding{/color}{/size}\n\n{font=NotoSansSC-Regular.otf}Andy Church{/font}\n\n\n\n{size=+12}{color=FF4444}Testing{/color}{/size}\n\n{font=Roboto-Regular.ttf}FerventWriter\n\nSku;Te\n\nJohan\n\neeveetron\n\nRoger Wallace Jr.{/font}\n\n\n\n{size=+12}{color=FF4444}Music{/color}{/size}\n\n{size=-5}{font=NotoSansSC-Regular.otf}\\"Atlantean Twilight\\", \\"Clean Soul\\", \\"Clear Waters\\", \\"Colorless Aura\\", \\"Gymnopedie No. 2\\", \\"Loss\\", \\"Lost Time\\", \\"Luminous Rain\\", \\"Moonstone\\", \\"Ossuary 2 - Turn\\", \\"Piece for Disaffected Piano One\\", \\"Piece for Disaffected Piano Two\\"\n\nKevin MacLeod (incompetech.com)\n\nLicensed under Creative Commons: By Attribution 3.0\n\nhttp://creativecommons.org/licenses/by/3.0/{/font}{/size}\n\n\n\n{size=+12}{color=FF4444}Sound Effects{/color}{/size}\n\n{size=-5}{font=NotoSansSC-Regular.otf}\\"Digging1.wav\\" by cameronmusic (freesound.org/people/cameronmusic/sounds/138411/)\n\n\\"Table Hit.mp3\\" by Dasgoat (freesound.org/people/Dasgoat/sounds/332034/)\n\n\\"Smashing, Wooden Fence, B.wav\\" by InspectorJ (freesound.org/people/InspectorJ/sounds/352204/)\n\n\\"OhDearScare.wav\\" by SirBedlam (freesound.org/people/SirBedlam/sounds/124954/)\n\n\\"Heartbeat.wav\\" by TobiasLudwig (freesound.org/people/TobiasLudwig/sounds/387072/)\n\nLicensed under Creative Commons: By Attribution 3.0\n\nhttp://creativecommons.org/licenses/by/3.0/{/font}{/size}\n\n\n\n{size=+12}{color=FF4444}{font=NotoSansSC-Regular.otf}简体中文{/color}{/size}{/font}\n\n{size=-8}{font=NotoSansSC-Regular.otf}LeanderLin{/size}{/font}\n\n\n\n{size=+12}{color=FF4444}Engine{/color}{/size}\n\n{size=-5}{font=NotoSansSC-Regular.otf}Made with {a=https://www.renpy.org/}Ren'Py{/a} 7.3.2.320.\n\nThis program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}.{/font}{/size}\n\n\n\n"
